fail_on_severity: 'low'
allow_licenses:
  - 'BSD-2-Clause'
  - 'BSD-3-Clause'
  - 'BSD-2-Clause AND BSD-3-Clause'
  - 'MIT'
  - 'Apache-2.0'
  - 'ISC'
  - 'Apache-2.0 AND MIT'
  - 'BlueOak-1.0.0'
  - '0BSD'
  - 'Python-2.0'
fail_on_scopes:
  - 'runtime'
  - 'development'
  - 'unknown'
license_check: true
vulnerability_check: true
allow_dependencies_licenses:
  - 'pkg:pypi/PyGithub'
  - 'pkg:pypi/psycopg2-binary'
