Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@azhogov 
azhogov
/
openvino
forked from openvinotoolkit/openvino
0
0
630
Code
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
openvino/azure-pipelines.yml
@azhogov
azhogov Update azure-pipelines.yml
Latest commit 7a6096b 6 days ago
 History
 2 contributors
@azhogov@SDxKeeper
60 lines (58 sloc)  1002 Bytes
  
jobs:
- job: TestLin
  timeoutInMinutes: 10
  pool:
    name: LIN_VMSS_VENV_F8S_WU2
  variables:
    system.debug: true
  steps:
  - checkout: none
    clean: true
    fetchDepth: 1
    lfs: false
    submodules: true
    path: openvino
  - script: |
      ls qqq
      echo $?
      ls .
      echo $?
    displayName: 'Exit code'
- job: TestMac
  timeoutInMinutes: 10
  pool:
    vmImage: 'macOS-10.15'
  variables:
    system.debug: true
  steps:
  - checkout: none
    clean: true
    fetchDepth: 1
    lfs: false
    submodules: true
    path: openvino
  - script: |
      ls qqq
      echo $?
      ls .
      echo $?
    displayName: 'Exit code'
- job: TestWin
  timeoutInMinutes: 10
  pool:
    name: WIN_VMSS_VENV_F8S_WU2
  variables:
    system.debug: true
  steps:
  - checkout: none
    clean: true
    fetchDepth: 1
    lfs: false
    submodules: true
    path: openvino
  - script: |
      dir qqq
      echo %errorlevel%
      cd .
      echo %errorlevel%
    displayName: 'Exit code'
© 2020 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
