jobs:
- job: MO_UT
  timeoutInMinutes: 0
  pool:
      vmImage: 'ubuntu-18.04'
  steps:
  - task: UsePythonVersion@0
    inputs:
        versionSpec: '3.6'
  - script: |
        cd model-optimizer
        mkdir ../mo-ut-logs
        python3 -m pip install setuptools
        python3 -m pip install unittest-xml-reporting
        python3 -m pip install -r requirements.txt
        python3 -m pip install -r requirements_dev.txt
        export PYTHONPATH=$PYTHONPATH:`pwd`
        export MO_ROOT=`pwd`
        env
        python3 -m xmlrunner discover -p *_test.py --output=../mo-ut-logs
    displayName: 'MO UT'

#IE_Lin
- job: IE_Lin
  timeoutInMinutes: 0
  pool:
      vmImage: 'ubuntu-18.04'
  steps:
  - script: |
        whoami
        uname -a
        lsb_release
        gcc --version
        env
        cat /proc/cpuinfo
        cat /proc/meminfo
        vmstat -s
        df
    displayName: 'System properties'
  - script: |
        sudo apt --assume-yes install libusb-1.0-0-dev
        python3 -m pip install -r ./inference-engine/ie_bridges/python/requirements.txt
#        sudo apt --assume-yes install cython3
#        curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip -o ninja-linux.zip
#        unzip ninja-linux.zip
#        sudo cp -v ninja /usr/local/bin/
    displayName: 'Install dependencies'
  - script: git submodule update --init --recursive
    displayName: 'Clone submodules'
  - script: git clone https://github.com/openvinotoolkit/testdata.git
    displayName: 'Clone testdata'
  - script: |
        mkdir dldt-build-release
        cd dldt-build-release
    displayName: 'Create build directory'
  - task: CMake@1
    inputs:
        workingDirectory: dldt-build-release
        cmakeArgs: .. -DVERBOSE_BUILD=ON -DCMAKE_BUILD_TYPE=Release -DENABLE_PYTHON=ON -DENABLE_LTO=ON -DENABLE_TESTS=ON
  - script: make -j2
#        cmakeArgs: .. -GNinja -DVERBOSE_BUILD=ON -DCMAKE_BUILD_TYPE=Release -DENABLE_PYTHON=ON -DENABLE_LTO=ON -DENABLE_TESTS=ON
#  - script: ninja
    workingDirectory: dldt-build-release
    displayName: 'Build IE'
  - script: |
        ls -al ../bin/intel64/Release/
    workingDirectory: dldt-build-release
    displayName: 'List files'
    continueOnError: true
  - script: |
        ../bin/intel64/Release/InferenceEngineUnitTests
    workingDirectory: dldt-build-release
    displayName: 'IE UT old'
    continueOnError: true
  - script: |
        ../bin/intel64/Release/ieUnitTests
    workingDirectory: dldt-build-release
    displayName: 'IE UT'
    continueOnError: true
  - script: |
        ../bin/intel64/Release/cpuUnitTests
    workingDirectory: dldt-build-release
    displayName: 'CPU UT'
    continueOnError: true
  - script: |
        ../bin/intel64/Release/gnaUnitTests
    workingDirectory: dldt-build-release
    displayName: 'GNA UT'
    continueOnError: true
  - script: |
        ../bin/intel64/Release/vpuUnitTests
    workingDirectory: dldt-build-release
    displayName: 'VPU UT'
    continueOnError: true
  - script: |
        ../bin/intel64/Release/ieFuncTests
    workingDirectory: dldt-build-release
    displayName: 'IE FuncTests'
    continueOnError: true
  - script: |
        ../bin/intel64/Release/MklDnnBehaviorTests
    workingDirectory: dldt-build-release
    displayName: 'MklDnnBehaviorTests'
    continueOnError: true
  - script: |
        export DATA_PATH=`pwd`/../testdata
        export MODELS_PATH=`pwd`/../testdata
        ../bin/intel64/Release/MklDnnFunctionalTests
    workingDirectory: dldt-build-release
    displayName: 'MklDnnFunctionalTests'
    continueOnError: true
  - script: |
        export DATA_PATH=`pwd`/../testdata
        export MODELS_PATH=`pwd`/../testdata
        ../bin/intel64/Release/InferenceEngineCAPITests
    workingDirectory: dldt-build-release
    displayName: 'IE CAPITests'
    continueOnError: true
  - script: |
        ../bin/intel64/Release/unit-test --gtest_print_time=1 --gtest_filter=-backend_api.config_unsupported
    workingDirectory: dldt-build-release
    displayName: 'nGraph UT'
    continueOnError: true

#IE_MAC
- job: IE_MAC
  timeoutInMinutes: 0
  pool:
      vmImage: 'macOS-10.14'
  variables:
      CC: gcc
      CXX: g++
      DL_SDK_TEMP: /tmp/
  steps:
  - task: UsePythonVersion@0
    inputs:
        versionSpec: '3.7'
  - script: |
        whoami
        uname -a
        gcc --version
        env
        xcrun --sdk macosx --show-sdk-version
        sysctl -a | grep machdep.cpu
    displayName: 'System properties'
  - script: |
        brew install ninja
        brew install cython
        brew install automake
    displayName: 'Install dependencies'
  - script: git submodule update --init --recursive
    displayName: 'Clone submodules'
  - script: git clone https://github.com/openvinotoolkit/testdata.git
    displayName: 'Clone testdata'
  - script: |
        mkdir dldt-build-release
        cd dldt-build-release
    displayName: 'Create build directory'
  - script: |
        export PATH="/usr/local/opt/cython/bin:$PATH"
        cmake .. -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12 -DCMAKE_POLICY_DEFAULT_CMP0068=NEW -DVERBOSE_BUILD=ON -DCMAKE_BUILD_TYPE=Release -DENABLE_PYTHON=ON -DENABLE_LTO=ON -DENABLE_TESTS=ON
    workingDirectory: dldt-build-release
    displayName: 'CMake'
  - script: make -j2
    workingDirectory: dldt-build-release
    displayName: 'Build IE'
  - script: |
        ls -al ../bin/intel64/Release/
    workingDirectory: dldt-build-release
    displayName: 'List files'
    continueOnError: true
  - script: |
        ../bin/intel64/Release/InferenceEngineUnitTests
    workingDirectory: dldt-build-release
    displayName: 'IE UT old'
    continueOnError: true
  - script: |
        ../bin/intel64/Release/ieUnitTests
    workingDirectory: dldt-build-release
    displayName: 'IE UT'
    continueOnError: true
  - script: |
        ../bin/intel64/Release/cpuUnitTests
    workingDirectory: dldt-build-release
    displayName: 'CPU UT'
    continueOnError: true
  - script: |
        ../bin/intel64/Release/vpuUnitTests
    workingDirectory: dldt-build-release
    displayName: 'VPU UT'
    continueOnError: true
  - script: |
        ../bin/intel64/Release/ieFuncTests
    workingDirectory: dldt-build-release
    displayName: 'IE FuncTests'
    continueOnError: true
  - script: |
        ../bin/intel64/Release/MklDnnBehaviorTests
    workingDirectory: dldt-build-release
    displayName: 'MklDnnBehaviorTests'
    continueOnError: true
  - script: |
        export DATA_PATH=`pwd`/../testdata
        export MODELS_PATH=`pwd`/../testdata
        ../bin/intel64/Release/MklDnnFunctionalTests
    workingDirectory: dldt-build-release
    displayName: 'MklDnnFunctionalTests'
    continueOnError: true
  - script: |
        export DATA_PATH=`pwd`/../testdata
        export MODELS_PATH=`pwd`/../testdata
        ../bin/intel64/Release/InferenceEngineCAPITests
    workingDirectory: dldt-build-release
    displayName: 'IE CAPITests'
    continueOnError: true
  - script: |
        ../bin/intel64/Release/unit-test --gtest_print_time=1 --gtest_filter=-backend_api.config_unsupported
    workingDirectory: dldt-build-release
    displayName: 'nGraph UT'
    continueOnError: true

#IE_Win
- job: IE_Win
  timeoutInMinutes: 0
  pool:
      vmImage: 'vs2017-win2016'
  steps:
  - script: |
        set
        wmic cpu list
        wmic logicaldisk get description,name
        wmic VOLUME list
    displayName: 'System properties'
#  - script: |
#        choco install ninja
#    displayName: 'Download ninja'
  - script: git submodule update --init --recursive
    displayName: 'Clone submodules'
  - script: |
        mkdir C:\c-dldt-build-release\bin
        mkdir dldt-build-release
        cd dldt-build-release
    displayName: 'Create build directory'
  - script: git clone https://github.com/openvinotoolkit/testdata.git
    workingDirectory: C:\c-dldt-build-release
    displayName: 'Clone testdata'
  - task: CMake@1
    inputs:
        workingDirectory: C:\c-dldt-build-release
        cmakeArgs: -G"Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DENABLE_LTO=ON -DENABLE_TESTS=ON $(Build.Repository.LocalPath)
  - script: cmake --build . --config Release -j2
    workingDirectory: C:\c-dldt-build-release
    displayName: 'Build IE VS2017'
  - script: |
        dir ..\bin\intel64\Release\
    workingDirectory: dldt-build-release
    displayName: 'List files'
    continueOnError: true
  - script: |
        set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
        ..\bin\intel64\Release\InferenceEngineUnitTests
    workingDirectory: dldt-build-release
    displayName: 'IE UT old'
    continueOnError: true
  - script: |
        set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
        ..\bin\intel64\Release\ieUnitTests
    workingDirectory: dldt-build-release
    displayName: 'IE UT'
    continueOnError: true
  - script: |
        set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
        ..\bin\intel64\Release\cpuUnitTests
    workingDirectory: dldt-build-release
    displayName: 'CPU UT'
    continueOnError: true
  - script: |
        set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
        ..\bin\intel64\Release\gnaUnitTests
    workingDirectory: dldt-build-release
    displayName: 'GNA UT'
    continueOnError: true
  - script: |
        set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
        ..\bin\intel64\Release\vpuUnitTests
    workingDirectory: dldt-build-release
    displayName: 'VPU UT'
    continueOnError: true
  - script: |
        set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
        ..\bin\intel64\Release\ieFuncTests
    workingDirectory: dldt-build-release
    displayName: 'IE FuncTests'
    continueOnError: true
  - script: |
        set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
        ..\bin\intel64\Release\MklDnnBehaviorTests
    workingDirectory: dldt-build-release
    displayName: 'MklDnnBehaviorTests'
    continueOnError: true
  - script: |
        set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;$(Build.Repository.LocalPath)\inference-engine\temp\opencv_4.3.0\opencv\bin;%PATH%
        set DATA_PATH=C:\c-dldt-build-release\testdata
        set MODELS_PATH=C:\c-dldt-build-release\testdata
        ..\bin\intel64\Release\MklDnnFunctionalTests
    workingDirectory: dldt-build-release
    displayName: 'MklDnnFunctionalTests'
    continueOnError: true
  - script: |
        set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;$(Build.Repository.LocalPath)\inference-engine\temp\opencv_4.3.0\opencv\bin;%PATH%
        set DATA_PATH=C:\c-dldt-build-release\testdata
        set MODELS_PATH=C:\c-dldt-build-release\testdata
        ..\bin\intel64\Release\InferenceEngineCAPITests
    workingDirectory: dldt-build-release
    displayName: 'IE CAPITests'
    continueOnError: true
  - script: |
        set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
        ..\bin\intel64\Release\unit-test --gtest_print_time=1 --gtest_filter=-backend_api.config_unsupported
    workingDirectory: dldt-build-release
    displayName: 'nGraph UT'
    continueOnError: true

#IE_Win_self
- job: IE_Win_self
  timeoutInMinutes: 0
  pool:
      name: Self-Hosted-Azure
      demands:
          - Agent.OS -equals Windows_NT
  steps:
  - script: |
        set
        wmic cpu list
        wmic logicaldisk get description,name
        wmic VOLUME list
    displayName: 'System properties'
#  - script: |
#        choco install ninja
#    displayName: 'Download ninja'
  - script: git submodule update --init --recursive
    displayName: 'Clone submodules'
  - script: |
        rd /Q /S C:\c-dldt-build-release
        mkdir C:\c-dldt-build-release\bin
        rd /Q /S dldt-build-release
        mkdir dldt-build-release
        cd dldt-build-release
    displayName: 'Create build directory'
  - script: git clone https://github.com/openvinotoolkit/testdata.git
    workingDirectory: C:\c-dldt-build-release
    displayName: 'Clone testdata'
  - task: CMake@1
    inputs:
        workingDirectory: C:\c-dldt-build-release
        cmakeArgs: -G"Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DENABLE_LTO=ON -DENABLE_TESTS=ON $(Build.Repository.LocalPath)
  - script: cmake --build . --config Release -j4
    workingDirectory: C:\c-dldt-build-release
    displayName: 'Build IE VS2019'
  - script: |
        set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
        ..\bin\intel64\Release\InferenceEngineUnitTests
    workingDirectory: dldt-build-release
    displayName: 'IE UT old'
    continueOnError: true
  - script: |
        set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
        ..\bin\intel64\Release\ieUnitTests
    workingDirectory: dldt-build-release
    displayName: 'IE UT'
    continueOnError: true
  - script: |
        set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
        ..\bin\intel64\Release\cpuUnitTests
    workingDirectory: dldt-build-release
    displayName: 'CPU UT'
    continueOnError: true
  - script: |
        set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
        ..\bin\intel64\Release\gnaUnitTests
    workingDirectory: dldt-build-release
    displayName: 'GNA UT'
    continueOnError: true
  - script: |
        set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
        ..\bin\intel64\Release\vpuUnitTests
    workingDirectory: dldt-build-release
    displayName: 'VPU UT'
    continueOnError: true
  - script: |
        set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
        ..\bin\intel64\Release\ieFuncTests
    workingDirectory: dldt-build-release
    displayName: 'IE FuncTests'
    continueOnError: true
  - script: |
        set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
        ..\bin\intel64\Release\MklDnnBehaviorTests
    workingDirectory: dldt-build-release
    displayName: 'MklDnnBehaviorTests'
    continueOnError: true
  - script: |
        set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;$(Build.Repository.LocalPath)\inference-engine\temp\opencv_4.3.0\opencv\bin;%PATH%
        set DATA_PATH=C:\c-dldt-build-release\testdata
        set MODELS_PATH=C:\c-dldt-build-release\testdata
        ..\bin\intel64\Release\MklDnnFunctionalTests
    workingDirectory: dldt-build-release
    displayName: 'MklDnnFunctionalTests'
    continueOnError: true
  - script: |
        set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;$(Build.Repository.LocalPath)\inference-engine\temp\opencv_4.3.0\opencv\bin;%PATH%
        set DATA_PATH=C:\c-dldt-build-release\testdata
        set MODELS_PATH=C:\c-dldt-build-release\testdata
        ..\bin\intel64\Release\InferenceEngineCAPITests
    workingDirectory: dldt-build-release
    displayName: 'IE CAPITests'
    continueOnError: true
  - script: |
        set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
        ..\bin\intel64\Release\unit-test --gtest_print_time=1 --gtest_filter=-backend_api.config_unsupported
    workingDirectory: dldt-build-release
    displayName: 'nGraph UT'
    continueOnError: true