jobs:
- job: Win
  timeoutInMinutes: 0
  pool:
    #vmImage: 'vs2017-win2016'
    name: WIN_VMSS_VENV_F8S
  variables:
    BUILD_TYPE: Release
    BUILD_DIR: D:\dldt-build
  steps:
  - script: |
      set
      wmic cpu list
      wmic logicaldisk get description,name
      wmic VOLUME list
    displayName: 'System properties'
  - script: git submodule update --init --recursive
    displayName: 'Clone submodules'
  - script: |
      rd /Q /S $(BUILD_DIR)
      mkdir $(BUILD_DIR)\bin
      rd /Q /S dldt-build
      mkdir dldt-build
    displayName: 'Create build directory'
  - task: CMake@1
    inputs:
      #cmakeArgs: -G"Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=$(BUILD_TYPE) -DENABLE_TESTS=ON $(Build.Repository.LocalPath)
      cmakeArgs: -G"Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=$(BUILD_TYPE) -DENABLE_TESTS=ON $(Build.Repository.LocalPath)
      workingDirectory: $(BUILD_DIR)
  - script: cmake --build . --config $(BUILD_TYPE) -j12
    workingDirectory: $(BUILD_DIR)
    displayName: 'Build IE VS2019'
  - script: dir ..\bin\intel64\$(BUILD_TYPE)\
    workingDirectory: dldt-build
    displayName: 'List files'
  - script: |
      set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
      ..\bin\intel64\$(BUILD_TYPE)\unit-test --gtest_print_time=1 --gtest_filter=-backend_api.config_unsupported:*IE_GPU*
    workingDirectory: dldt-build
    displayName: 'nGraph UT'
    continueOnError: false
  - script: |
      set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
      ..\bin\intel64\$(BUILD_TYPE)\InferenceEngineUnitTests
    workingDirectory: dldt-build
    displayName: 'IE UT old'
    continueOnError: false
  - script: |
      set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
      ..\bin\intel64\$(BUILD_TYPE)\ieUnitTests
    workingDirectory: dldt-build
    displayName: 'IE UT'
    continueOnError: false
  - script: |
      set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
      ..\bin\intel64\$(BUILD_TYPE)\cpuUnitTests
    workingDirectory: dldt-build
    displayName: 'CPU UT'
    continueOnError: false
  - script: |
      set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
      ..\bin\intel64\$(BUILD_TYPE)\gnaUnitTests
    workingDirectory: dldt-build
    displayName: 'GNA UT'
    continueOnError: false
  - script: |
      set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
      ..\bin\intel64\$(BUILD_TYPE)\vpuUnitTests
    workingDirectory: dldt-build
    displayName: 'VPU UT'
    continueOnError: false
  - script: |
      set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
      ..\bin\intel64\$(BUILD_TYPE)\ieFuncTests
    workingDirectory: dldt-build
    displayName: 'IE FuncTests'
    continueOnError: false
  - script: |
      set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
      ..\bin\intel64\$(BUILD_TYPE)\cpuFuncTests
    workingDirectory: dldt-build
    displayName: 'CPU FuncTests'
    continueOnError: false
  - script: |
      set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;%PATH%
      ..\bin\intel64\$(BUILD_TYPE)\MklDnnBehaviorTests
    workingDirectory: dldt-build
    displayName: 'MklDnnBehaviorTests'
    continueOnError: false
  - script: git clone https://github.com/openvinotoolkit/testdata.git
    workingDirectory: $(BUILD_DIR)
    displayName: 'Clone testdata'
  - script: |
      set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;$(Build.Repository.LocalPath)\inference-engine\temp\opencv_4.3.0\opencv\bin;%PATH%
      set DATA_PATH=$(BUILD_DIR)\testdata
      set MODELS_PATH=$(BUILD_DIR)\testdata
      ..\bin\intel64\$(BUILD_TYPE)\MklDnnFunctionalTests --gtest_filter=-smoke_MobileNet/ModelTransformationsTest.LPT/mobilenet_v2_tf_depthwise_batch1_inPluginDisabled_inTestDisabled_asymmetric*
    workingDirectory: dldt-build
    displayName: 'MklDnnFunctionalTests'
    continueOnError: false
  - script: |
      set PATH=$(Build.Repository.LocalPath)\inference-engine\temp\tbb\bin;$(Build.Repository.LocalPath)\inference-engine\temp\opencv_4.3.0\opencv\bin;%PATH%
      set DATA_PATH=$(BUILD_DIR)\testdata
      set MODELS_PATH=$(BUILD_DIR)\testdata
      ..\bin\intel64\$(BUILD_TYPE)\InferenceEngineCAPITests
    workingDirectory: dldt-build
    displayName: 'IE CAPITests'
    continueOnError: false
