jobs:

# IE_MAC
- job: IE_MAC
  timeoutInMinutes: 0
  pool:
    vmImage: 'macOS-10.15'
  variables:
    CC: gcc
    CXX: g++
    BUILD_TYPE: Debug
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - script: |
      whoami
      uname -a
      gcc --version
      env
      xcrun --sdk macosx --show-sdk-version
      sysctl -a | grep machdep.cpu
    displayName: 'System properties'
  - script: |
      brew install ninja
      brew install cython
      brew install automake
    displayName: 'Install dependencies'
  - script: git submodule update --init --recursive
    displayName: 'Clone submodules'
  - script: |
      mkdir dldt-build
      cd dldt-build
    displayName: 'Create build directory'
  - script: |
      export PATH="/usr/local/opt/cython/bin:$PATH"
      cmake .. -DVERBOSE_BUILD=ON -DCMAKE_BUILD_TYPE=$(BUILD_TYPE) -DENABLE_PYTHON=ON -DENABLE_TESTS=ON
    workingDirectory: dldt-build
    displayName: 'CMake'
  - script: make -j3
    workingDirectory: dldt-build
    displayName: 'Build IE'
  - script: ls -al ../bin/intel64/$(BUILD_TYPE)/
    workingDirectory: dldt-build
    displayName: 'List files'
  - script: ../bin/intel64/$(BUILD_TYPE)/unit-test --gtest_print_time=1 --gtest_filter=-backend_api.config_unsupported:*IE_GPU*:IE_CPU.onnx_model_sigmoid
    workingDirectory: dldt-build
    displayName: 'nGraph UT'
    continueOnError: true
  - script: ../bin/intel64/$(BUILD_TYPE)/InferenceEngineUnitTests
    workingDirectory: dldt-build
    displayName: 'IE UT old'
    continueOnError: true
  - script: ../bin/intel64/$(BUILD_TYPE)/ieUnitTests
    workingDirectory: dldt-build
    displayName: 'IE UT'
    continueOnError: true
  - script: ../bin/intel64/$(BUILD_TYPE)/cpuUnitTests
    workingDirectory: dldt-build
    displayName: 'CPU UT'
    continueOnError: true
  - script: ../bin/intel64/$(BUILD_TYPE)/vpuUnitTests
    workingDirectory: dldt-build
    displayName: 'VPU UT'
    continueOnError: true
  - script: ../bin/intel64/$(BUILD_TYPE)/ieFuncTests
    workingDirectory: dldt-build
    displayName: 'IE FuncTests'
    continueOnError: true
  - script: ../bin/intel64/$(BUILD_TYPE)/MklDnnBehaviorTests
    workingDirectory: dldt-build
    displayName: 'MklDnnBehaviorTests'
    continueOnError: true
  - script: git clone https://github.com/openvinotoolkit/testdata.git
    displayName: 'Clone testdata'
  - script: |
      export DATA_PATH=`pwd`/../testdata
      export MODELS_PATH=`pwd`/../testdata
      ../bin/intel64/$(BUILD_TYPE)/MklDnnFunctionalTests --gtest_filter=-*smoke_MobileNet/ModelTransformationsTest.LPT/mobilenet_v2_tf_depthwise_batch1_inPluginDisabled_inTestDisabled_asymmetric*:*smoke_SingleLayerTransformationsTestFP16/SingleLayerTransformationsTest.LPT/PoolingTestModel*:*smoke_Inception/ModelTransformationsTest.LPT/inception_v3_tf_batch1_inPluginDisabled_inTestDisabled_asymmetric*
    workingDirectory: dldt-build
    displayName: 'MklDnnFunctionalTests'
    continueOnError: true
  - script: |
      export DATA_PATH=`pwd`/../testdata
      export MODELS_PATH=`pwd`/../testdata
      ../bin/intel64/$(BUILD_TYPE)/InferenceEngineCAPITests
    workingDirectory: dldt-build
    displayName: 'IE CAPITests'
    continueOnError: true