name: 'Setup apt'
description: 'Setups apt manager with common options'

runs:
  using: 'composite'
  steps:
    - name: Set Retry options
      shell: bash
      run: |
        if [ "$(id -u)" -eq 0 ]; then
          echo 'Acquire::Retries "10";' > /etc/apt/apt.conf
        else
          sudo sh -c "echo 'Acquire::Retries "10";' > /etc/apt/apt.confs"
        fi

    - name: Set Install options
      shell: bash
      run: |
        if [ "$(id -u)" -eq 0 ]; then
          echo 'APT::Get::Assume-Yes "true";' >> /etc/apt/apt.conf
          echo 'APT::Get::Fix-Broken "true";' >> /etc/apt/apt.conf
          echo 'APT::Get::no-install-recommends "true";' >> /etc/apt/apt.conf
        else
          sudo sh -c "echo 'APT::Get::Assume-Yes "true";' >> /etc/apt/apt.conf"
          sudo sh -c "echo 'APT::Get::Fix-Broken "true";' >> /etc/apt/apt.conf"
          sudo sh -c "echo 'APT::Get::no-install-recommends "true";' >> /etc/apt/apt.conf"
        fi

    - name: Set Cache options
      shell: bash
      run: |
        if [ "$(id -u)" -eq 0 ]; then
          echo 'APT::Archives::MinAge "2";' >> /etc/apt/apt.conf
          echo 'APT::Archives::MaxAge "30";' >> /etc/apt/apt.conf
          echo 'APT::Archives::MaxSize "500";' >> /etc/apt/apt.conf
          # do not remove deb packages:
          rm /etc/apt/apt.conf.d/docker-clean
        else
          sudo sh -c "echo 'APT::Archives::MinAge "2";' >> /etc/apt/apt.conf"
          sudo sh -c "echo 'APT::Archives::MaxAge "30";' >> /etc/apt/apt.conf"
          sudo sh -c "echo 'APT::Archives::MaxSize "500";' >> /etc/apt/apt.conf"
          # do not remove deb packages:
          sudo rm /etc/apt/apt.conf.d/docker-clean
        fi
