name: 'Create manifest'
description: 'Creates manifest containing versions of the product and the corresponding repositories'
inputs:
  repos:
    description: "Multi-line list of repositories to include to manifest"
    required: true
  save_to:
    description: "Path to save manifest to"
    required: true
  action_path:
    description: "Action path, if not set - taken from github context"
    required: false
  target_arch:
    description: "Target architecture"
    required: true
  build_type:
    description: "Build type: release | debug | release_with_debug"
    required: true


runs:
  using: "composite"
  steps:
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: "${{ inputs.action_path && inputs.action_path || github.action_path }}/requirements.txt"
        update-setuptools: "false"
        update-wheel: "false"

    - name: 'Create manifest'
      id: create_manifest
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: >-
        python ${{ inputs.action_path && inputs.action_path || github.action_path }}/create_manifest.py
        --target_arch "${{ inputs.target_arch }}" --build_type "${{ inputs.build_type }}"
        --save_to "${{ inputs.save_to }}" -r "${{ inputs.repos }}"
      env:
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
