jobs:
- job: nGraph_ONNX_Lin

  # About 150% of total time
  timeoutInMinutes: 600

  pool:
    name: LIN_VMSS_VENV_F8S_WU2

  variables:
    system.debug: true
    VSTS_HTTP_RETRY: 5
    VSTS_HTTP_TIMEOUT: 200
    WORKERS_NUMBER: 8
    BUILD_TYPE: Release
    REPO_DIR: $(Build.Repository.LocalPath)
    WORK_DIR: $(Pipeline.Workspace)/_w
    MODELS_DIR: /mnt/onnxtestdata/models

  steps:
  - checkout: self
    clean: true
    lfs: false
    submodules: recursive
    path: openvino

  - script: |
      curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2019-06-01"
      whoami
      uname -a
      which python3
      python3 --version
      gcc --version
      lsb_release
      env
      cat /proc/cpuinfo
      cat /proc/meminfo
      cat /etc/fstab
      vmstat -s
      df
      lsblk -o NAME,HCTL,SIZE,MOUNTPOINT | grep -i "sd"
    displayName: 'System info'

  - script: |
      rm -rf $(WORK_DIR) ; mkdir $(WORK_DIR)
      ls -alR /mnt/onnxtestdata/
    displayName: 'Make dir'

  - script: |
      #ngraph/python/tests/test_onnx/model_zoo_preprocess.sh -m $(MODELS_DIR) -e -f
    displayName: 'model_zoo_preprocess'
    enabled: false

  - script: |
      #wget https://github.com/onnx/models/archive/master.zip -O "$(MODELS_DIR)/onnx_model_zoo.zip" --quiet
      #unzip "$(MODELS_DIR)/onnx_model_zoo.zip" -d "$(MODELS_DIR)/onnx_model_zoo"
      #rm "$(MODELS_DIR)/onnx_model_zoo.zip"
    displayName: 'Clone ONNX models'
    enabled: false

  - script: |
      #wget https://onnxruntimetestdata.blob.core.windows.net/models/20191107.zip -O "$(MODELS_DIR)/msft.zip" --quiet
      #unzip "$(MODELS_DIR)/msft.zip" -d "$(MODELS_DIR)/msft"
      #rm "$(MODELS_DIR)/msft.zip"
    displayName: 'Clone MSFT models'
    enabled: false

  - script: docker build --tag=openvino-onnx-ci-image --file=.ci/openvino-onnx/Dockerfile .
    displayName: 'Docker build'

  - script: docker run --name openvino-onnx-ci-container --volume $(MODELS_DIR):/root/.onnx/model_zoo --volume $(MODELS_DIR)/msft:/root/.onnx/model_zoo/MSFT openvino-onnx-ci-image
    displayName: 'Docker run tests'
    enabled: false

