name: Documentation
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build_Doc:
    if: github.repository == 'openvinotoolkit/openvino'
    runs-on: ubuntu-22.04
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@v2
        with:
          submodules: true
          lfs: true

      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1

      - name: Cache doxygen make
        id: cache_doxygen_make
        uses: actions/cache@v3
        with:
          path: doxygen-build
          key: build-doxygen-cache

      - name: Cache python requirements
        id: cache_python_requirements
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: doc-python-requirements

      - name: Install apt-get tools
        # install doc dependencies
        uses: tecolicom/actions-use-apt-tools@v1
        with:
          tools: graphviz texlive liblua5.2-0

      - name: Install dependencies
        run: |
          set -e
          cd docs
          python3 -m pip install -r requirements.txt --user
          cd openvino_sphinx_theme
          python3 setup.py install --user
          cd ../..
          # install doxyrest
          wget https://github.com/vovkos/doxyrest/releases/download/doxyrest-2.1.3/doxyrest-2.1.3-linux-amd64.tar.xz
          tar -xf doxyrest-2.1.3-linux-amd64.tar.xz
          echo "$(pwd)/doxyrest-2.1.3-linux-amd64/bin/" >> $GITHUB_PATH
          # install doxygen
          mkdir doxygen
          cd doxygen
          git clone --depth 1 https://github.com/doxygen/doxygen.git -b Release_1_9_2
          cmake -S doxygen -B ../doxygen-build
          cmake --build ../doxygen-build -j`nproc`
          sudo cmake --build ../doxygen-build --target install

      - name: CMake doc
        run: |
          cmake -DENABLE_INTEL_MYRIAD_COMMON=OFF -DENABLE_DOCS=ON -DENABLE_PYTHON=ON -DCMAKE_BUILD_TYPE=Release -B build

      - name: Cache documentation
        id: cache_sphinx_docs
        uses: actions/cache@v3
        with:
          path: build/docs/_build/.doctrees
          key: sphinx-docs-cache
      
      - name: Build doc
        run: |
          cmake --build build --target sphinx_docs -j`nproc`
      
      - name: Archive HTML
        run: |
          zip -r openvino_html.zip _build
        working-directory: build/docs
      
      - name: Run Pytest
        run: |
          pytest --doxygen="./build/docs/doxygen.log" \
                 --include_pot \
                 --sphinx="./build/docs/sphinx.log" \
                 --suppress-warnings="./docs/suppress_warnings.txt" \
                 --confcutdir="./docs/scripts/tests/" \
                 --html="./build/docs/_artifacts/doc-generation.html" \
                 --doxygen-strip="$(pwd)" \
                 --sphinx-strip="$(pwd)/build/docs/rst" \
                 --doxygen-xfail="./docs/doxygen-xfail.txt" \
                 --self-contained-html ./docs/scripts/tests/test_docs.py

      - name: 'Upload test results'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: openvino_doc_pytest
          path: build/docs/_artifacts/
      
      - name: 'Upload doxygen.log'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: doxygen_log
          path: build/docs/doxygen.log

      - name: 'Upload sphinx.log'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: sphinx_log
          path: build/docs/sphinx.log

      - name: 'Upload html'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: openvino_html
          path: build/docs/openvino_html.zip
