name: Test Cache WF
on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - master

concurrency:
  # github.ref is not unique in post-commit
  group: ${{ github.event_name == 'push' && github.run_id || github.ref }}-cache-test
  cancel-in-progress: true

jobs:
  Build:
    defaults:
      run:
        shell: bash
    runs-on: aks-linux-4-cores-16gb
    container:
      image: openvinogithubactions.azurecr.io/dockerhub/ubuntu:20.04
      volumes:
        - /mount:/mount
    env:
      OPENVINO_REPO: /__w/openvino/openvino/openvino
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.OPENVINO_REPO }}

      - name: Test preconditions
        run: |
          mkdir -p /__w/tmp/test_cache
          echo test > /__w/tmp/test_cache/file.txt
          mkdir -p /mount/gha_test_cache
          pushd /__w/tmp/test_cache
            tar -czvf /mount/gha_test_cache/test_cache_$(date '+%Y%m%d%S').cache *
          popd
          ls -la /mount/gha_test_cache

      - name: Test Local Action
        id: test-action
        uses: ./openvino/.github/actions/cache
        with:
          cache_path: /mount/gha_test_cache
          path: /__w/cache
          key: "test"

      - name: Print Output
        run: |
          ls -la /__w/cache
          echo "${{ steps.test-action.outputs.cache-file }}"