name: Test Cache WF
on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - master

concurrency:
  # github.ref is not unique in post-commit
  group: ${{ github.event_name == 'push' && github.run_id || github.ref }}-cache-test
  cancel-in-progress: true

jobs:
  Build:
    defaults:
      run:
        shell: bash
    runs-on: aks-linux-4-cores-16gb
    container:
      image: openvinogithubactions.azurecr.io/dockerhub/ubuntu:20.04
      volumes:
        - /mount:/mount
    env:
      OPENVINO_REPO: /__w/openvino/openvino/openvino
      CACHE_REMOTE: /mount/caches/gha_test_cache
      CACHE_LOCAL: /__w/cache
      CACHE_TMP: /__w/tmp/test_cache

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.OPENVINO_REPO }}

      - name: Test preconditions
        run: |
          mkdir -p ${CACHE_TMP}
          echo test > ${CACHE_TMP}/file.txt
          mkdir -p ${CACHE_REMOTE}
          pushd ${CACHE_TMP}
            tar -czvf ${CACHE_REMOTE}/test_cache_$(date '+%Y%m%d%S').cache *
          popd
          ls -la ${CACHE_REMOTE}

      - name: Test Local Action
        id: test-action
        uses: ./openvino/.github/actions/cache
        with:
          cache_path: ${{ env.CACHE_REMOTE }}
          path: ${{ env.CACHE_LOCAL }}
          key: ${{ runner.os }}-${{ runner.arch }}-test-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-test-cache
            test-cache
            ${{ runner.os }}-${{ runner.arch }}-test-cache

      - name: Print Output
        run: |
          ls -la ${CACHE_LOCAL}
          echo "${{ steps.test-action.outputs.cache-file }}"