name: PR Commits
on: [pull_request]

jobs:
  Checks:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: PR commits
        run: python .github/org_control/check_pr.py --pr=${{ github.event.number }} --check-commits

