name: Code Style
on: [push, pull_request]

jobs:
  nGraph:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install clang-format-3.9
        run: sudo apt --assume-yes install clang-format-3.9

      - name: CMake
        run: |
          mkdir ngraph-build
          cd ngraph-build
          cmake ../ngraph

      - name: Check
        run: |
          make style-check
        working-directory: ngraph-build

      - name: apply-code-format
        if: ${{ failure() }}
        run: |
          ../ngraph/maint/apply-code-format.sh
        working-directory: ngraph-build
