name: Code Style Java
on: [push, pull_request]

jobs:
  InferenceEngine:
    runs-on: ubuntu-18.04
    steps:
      - name: Check java code style
        run: |
          ngraph/maint/codestyle_check.sh
          git diff >java_code_style_diff.patch
