name: Code snippets
on:
  push:
    paths:
      - 'openvino/.github/workflows/code_snippets.yml'
      - 'openvino/docs/snippets/**'
  pull_request:
    paths:
      - 'openvino/.github/workflows/code_snippets.yml'
      - 'openvino/docs/snippets/**'

jobs:
  Build_Snippets:
    if: github.repository == 'openvinotoolkit/openvino'
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-22.04', 'macos-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true

      - name: Check cmake
        run: |
          which cmake
          cmake --version

      - name: CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
      
      - name: Build snippets
        run: |
          cmake --build . --target ie_docs_snippets -j`nproc`
        working-directory: build
