name: Code coverage
on:
  push:
    branches:
      - master
      - releases/*
    paths-ignore:
      - docs/
      - /**/docs/*
      - /**/*.md
      - README.md
      - /**/layer_tests_summary/**
  pull_request:
    branches:
      - master
      - releases/*
    paths-ignore:
      - docs/
      - /**/docs/*
      - /**/*.md
      - README.md
      - /**/layer_tests_summary/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Coverage:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Ubuntu gcc", os: ubuntu-latest-16-cores, cc: "gcc", cxx: "g++" }

    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      # - name: Setup Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'

      #- name: Setup GNinja
      #  uses: ashutoshvarma/setup-ninja@master
      #  with:
      #    version: 1.10.2
      
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 50G

      - name: Install build dependencies
        run: |
          sudo apt --assume-yes update
          sudo -E ${{ github.workspace }}/install_build_dependencies.sh
          sudo apt --assume-yes install lcov
      
      - name: Install python dependencies
        run: |
          pip install --upgrade pip
          pip install -r ${{ github.workspace }}/src/frontends/tensorflow_lite/tests/requirements.txt
          pip install -r ${{ github.workspace }}/src/bindings/python/src/compatibility/openvino/requirements-dev.txt
          pip install -r ${{ github.workspace }}/src/bindings/python/wheel/requirements-dev.txt
     #     pip install -r ${{ github.workspace }}/src/frontends/tensorflow/tests/requirements.txt
     #     pip install -r ${{ github.workspace }}/src/frontends/tensorflow/tests/requirements.txt
     #     pip install -r ${{ github.workspace }}/src/bindings/python/requirements.txt
     #     pip install -r ${{ github.workspace }}/src/frontends/paddle/tests/requirements.txt
     #     pip install -r ${{ github.workspace }}/src/frontends/onnx/tests/requirements.txt
     #     pip install -r ${{ github.workspace }}/tools/mo/requirements.txt
     #     pip install -r ${{ github.workspace }}/tools/mo/requirements_dev.txt

     # - name: ls all
     #   run: |
     #     ls -laR .
     #     echo $GITHUB_WORKSPACE
     #     echo ${{ github.workspace }}
      
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Build OpenVINO with CMake
        uses: ashutoshvarma/action-cmake-build@master
        with:
          cc: ${{ matrix.config.cc }}
          cxx: ${{ matrix.config.cxx }}
          configure-options: >
            -GNinja
            -DENABLE_PYTHON=ON
            -DCMAKE_VERBOSE_MAKEFILE=ON
            -DENABLE_STRICT_DEPENDENCIES=OFF
            -DENABLE_REQUIREMENTS_INSTALL=OFF
            -DENABLE_FASTER_BUILD=ON
            -DENABLE_OV_ONNX_FRONTEND=OFF
            -DENABLE_TESTS=ON
            -DENABLE_COVERAGE=ON
            -DCMAKE_C_COMPILER_LAUNCHER=ccache
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
            -DCMAKE_C_LINKER_LAUNCHER=ccache
            -DCMAKE_CXX_LINKER_LAUNCHER=ccache
          build-type: Release
          parallel: ${{ steps.cpu-cores.outputs.count }}
      
      - name: Run OV core tests
        run: ${{ github.workspace }}/bin/intel64/Release/ov_core_unit_tests

      - name: Build coverage with CMake
        uses: ashutoshvarma/action-cmake-build@master
        with:
          cc: ${{ matrix.config.cc }}
          cxx: ${{ matrix.config.cxx }}
          target: ov_coverage
          configure-options: -DCMAKE_VERBOSE_MAKEFILE=ON

            #- name: Generate raport
            #run: |
            # lcov --capture --directory . --output-file coverage.info
            #genhtml coverage.info --output-directory coverage-report

      - name: Collect coverage
        uses: codecov/codecov-action@v3
        with:
          verbose: true
