name: Code coverage
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone OpenVINO
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          mkdir build

          sudo apt update
          sudo apt --assume-yes install lcov
          pip install coverage
          pip install -r src/bindings/python/src/compatibility/openvino/requirements-dev.txt
          pip install -r src/bindings/python/wheel/requirements-dev.txt

          chmod +x install_build_dependencies.sh
          sudo -E ./install_build_dependencies.sh

      - name: Build OpenVINO
        run: |
          cmake -DCMAKE_VERBOSE_MAKEFILE=ON \
                -DENABLE_INTEL_MYRIAD_COMMON=OFF \
                -DENABLE_OV_ONNX_FRONTEND=ON \
                -DCMAKE_BUILD_TYPE=Release \
                -DENABLE_FASTER_BUILD=ON \
                -DENABLE_TESTS=ON \
                -DENABLE_PYTHON=ON \
                -DENABLE_COVERAGE=ON \
                -DENABLE_INTEL_GPU=OFF \
                -B build
          cmake --build build --parallel $(nproc --all) 

      - name: ls all
        run:  ls -laR .

      - name: Run Tests
        run: |
          ctest -V
      - name: Build coverage
        run:  cmake --build build --target ov_coverage

      - name: ls files
        run: ls -laR

      - name: Generate raport
        run: |
          lcov --capture --directory . --output-file coverage.info
          genhtml coverage.info --output-directory coverage-report

      - name: Collect coverage
        uses: codecov/codecov-action@v3
        with:
          verbose: true
