name: Code coverage
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Coverage:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install lcov dependency
        run: |
          sudo apt --assume-yes update
          sudo apt --assume-yes install lcov
      - name: CMake configure
        run: cmake -DENABLE_INTEL_MYRIAD_COMMON=OFF -DCMAKE_BUILD_TYPE=Release -DENABLE_FASTER_BUILD=ON -DENABLE_OV_ONNX_FRONTEND=ON -DENABLE_TESTS=ON -DENABLE_COVERAGE=ON -DENABLE_INTEL_GPU=OFF -B build

      - name: Build OpenVINO
        run:  cmake --build build --target all --parallel $(nproc --all)

      - name: ls all
        run:  ls -laR .

      - name: Run Core tests
        run: ctest -V -L OV

      - name: Run IR tests
        run: ctest -V -L IR_FE

      - name: Run Tensorflow tests
        run: ctest -V -L TF_FE

      - name: Run ONNX tests
        run: ctest -V -L ONNX_FE

      - name: Run Paddle tests
        run: ctest -V -L PADDLE_FE

      - name: Build coverage
        run:  cmake --build build --target ov_coverage

      - name: Generate raport
        run: |
          lcov --capture --directory . --output-file coverage.info
          genhtml coverage.info --output-directory coverage-report
      - name: Collect coverage
        uses: codecov/codecov-action@v3
        with:
          verbose: true