name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@95b6fa4e6b4bea7fe350fea69ef04dc294efad1c
        with:
          config-file: './.github/dependency_review.yml'
