name: Files Size
on: [push, pull_request]

jobs:
  Check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        
      - name: ls
        run: |
          git ls-tree -r -t -l --full-name HEAD | sort -n -r -k 4

      - name: ls lfs
        run: |
          git lfs ls-files --size
