name: Linux developer workflow for CPU plugin (Ubuntu 20.04)
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/linux_cpu_dev.yml'
      - 'src/common/snippets/**'
      - 'src/plugins/intel_cpu/src/nodes/subgraph.cpp'
      - 'src/plugins/intel_cpu/src/nodes/subgraph.h'
      - 'src/plugins/intel_cpu/src/emitters/snippets/**'
      - 'src/plugins/intel_cpu/src/emitters/tpp/**'
      - 'src/plugins/intel_cpu/src/transformations/snippets/**'
      - 'src/plugins/intel_cpu/src/transformations/tpp/**'

concurrency:
  group: ${{ github.event_name == 'push' && github.run_id || github.ref }}-linux-cpu-dev-2
  cancel-in-progress: true

permissions: read-all

jobs:
  Test-job-1:
    if: ${{ github.event_name == 'workflow_dispatch' || !contains(github.event.pull_request.title, 'GHA') }}
    timeout-minutes: 150
    defaults:
      run:
        shell: bash
    runs-on: aks-linux-16-cores-32gb
    steps:
      - name: Test PR triggering
        env:
          PR_NAME: ${{ toJson(github.event.pull_request.title) }}
          DO_CONTAIN: ${{ contains(github.event.pull_request.title, 'GHA') }}
        run: |
          echo "pr name:" \
          "$PR_NAME" \
          ", do_contain=" \
          "$DO_CONTAIN"
  Test-job-2:
    if: ${{ contains(github.event.pull_request.title, 'GHA') }}
    timeout-minutes: 150
    defaults:
      run:
        shell: bash
    runs-on: aks-linux-16-cores-32gb
    steps:
      - name: Test PR triggering
        env:
          PR_NAME: ${{ toJson(github.event.pull_request.title) }}
          DO_CONTAIN: ${{ contains(github.event.pull_request.title, 'GHA') }}
          PR: ${{ toJson(github.event.pull_request) }}
        run: |
          echo "pr name:" \
          "$PR_NAME" \
          ", do_contain=" \
          "$DO_CONTAIN" \
          "$PR"
