name: OVC
on:
  push:
    paths:
      - 'tools/ovc/**'
      - '.github/workflows/ovc.yml'
    branches:
      - 'master'
      - 'releases/**'
  pull_request:
    paths:
      - 'tools/ovc/**'
      - '.github/workflows/ovc.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Pylint-UT:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          # For UT
          pip install unittest-xml-reporting==3.0.2

        working-directory: tools/ovc

      - name: Pylint-OVC
        run: pylint -d C,R,W openvino/tools/ovc
        working-directory: tools/ovc