on: [push, pull_request]

jobs:
  ShellCheck:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install ShellCheck
        run: sudo apt --assume-yes install shellcheck

      - name: Install dependencies
        run: |
          sudo apt --assume-yes install libusb-1.0-0-dev
          python3 -m pip install -r ./inference-engine/ie_bridges/python/requirements.txt

      - name: CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: ShellCheck
        run: make ie_shellcheck
        working-directory: build

