name: Windows (Intel DPC++ Compiler, Python 3.11, Release)
on:
  workflow_dispatch:
  pull_request:
  merge_group:
concurrency:
  # github.ref is not unique in post-commit
  group: ${{ github.event_name == 'push' && github.run_id || github.ref }}-windows-dpcpp
  cancel-in-progress: true

permissions: read-all

env:
    TARGET_BRANCH: ${{ github.base_ref || github.event.merge_group.base_ref || github.ref }}

jobs:
  Smart_CI:
    runs-on: ubuntu-latest
    outputs:
      affected_components: "${{ steps.smart_ci.outputs.affected_components }}"
      skip_workflow: "${{ steps.smart_ci.outputs.skip_workflow }}"
      target_branch: ${{ steps.set_target_branch.outputs.target_branch }}
    steps:
      - name: checkout action
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          sparse-checkout: .github/actions/smart-ci

      - name: Get affected components
        id: smart_ci
        uses: ./.github/actions/smart-ci
        with:
          repository: ${{ github.repository }}
          pr: ${{ github.event.number }}
          commit_sha: ${{ github.sha }}
          ref_name: ${{ github.ref_name }}
          component_pattern: "category: (.*)"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          skip_when_only_listed_labels_set: 'docs'
          skip_when_only_listed_files_changed: '*.md,*.rst,*.png,*.jpg,*.svg,*/layer_tests_summary/*,*/conformance/*'

      - name: Get target branch
        id: set_target_branch
        run: |
          echo "target_branch=${TARGET_BRANCH#refs/heads/}" >> $GITHUB_OUTPUT

  Build:
    needs: [ Smart_CI ]
    if: "!needs.smart_ci.outputs.skip_workflow"
    uses: ./.github/workflows/job_build_windows.yml
    with:
      runner: 'aks-win-16-cores-32gb'
      affected-components: ${{ needs.smart_ci.outputs.affected_components }}
      build-type: 'Release'
      target-branch: ${{ needs.smart_ci.outputs.target_branch }}
      compiler-type: 'DPCPP'


  Overall_Status:
    name: ci/gha_overall_status_windows_dpcpp
    needs: [ Smart_CI, Build ]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check status of all jobs
        if: >-
          ${{
            contains(needs.*.result, 'failure') ||
            contains(needs.*.result, 'cancelled')
          }}
        run: exit 1
